services:
  - docker
language: java
sudo: false
install: true
jdk: oraclejdk8
script: 
  - ./travis.sh -Dbuildtime.output.log=true
before_install:
  - curl -OfsSL https://github.com/DTStax/Roolkeeper/master/travis.sh
  - chmod +x travis.sh
cache:
  directories:
    - .autoconf
    - $HOME/.m2
